version: "3.7"
services:
  dashboard:
    image: y:latest
    ports:
      - "4201:4200"
    volumes:
      - "/app/node_modules"
      - ".:/app"
    environment:
      - BACKEND_API_URL=192.168.0.105,9000